# Generated by Django 5.0.4 on 2024-04-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('telefone', models.CharField(max_length=20)),
                ('uf', models.TextField(max_length=2)),
                ('cep', models.TextField(max_length=10)),
                ('cidade', models.TextField(max_length=80)),
                ('bairro', models.TextField(max_length=80)),
                ('rua', models.TextField(max_length=80)),
                ('numero', models.IntegerField()),
            ],
        ),
    ]
